-- DDL mínimo inferido dos repositories; o DDL original não está versionado.
-- Complementado por src/config/registro-glicose-schema.sql.
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  tipo_login TEXT NOT NULL,
  tipo_usuario TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS periodo (
  id_periodo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS registroglicose (
  id_registro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT NOT NULL REFERENCES usuario(id_usuario),
  nivel_glicose DECIMAL(10,2) NOT NULL,
  data_hora TIMESTAMP NOT NULL,
  id_periodo INT NOT NULL REFERENCES periodo(id_periodo)
);
